name: Release and Tag package for Release

on:
  push:
    branches:
      - 'development'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# Development releases will package release then update development to a new release

jobs:
  release-Package:
    name: Up Version package and release
    if: github.ref == 'refs/heads/development'    
    uses: realitycollective/reusableworkflows/.github/workflows/tagrelease.yml@main
    with:
      build-target: windows
    secrets: inherit